group:
  repos: |
    neurobagel/annotation_tool
    neurobagel/api
    neurobagel/bagel-cli
    neurobagel/bagelschema
    neurobagel/bulk_annotations
    neurobagel/browbids
    neurobagel/documentation
    neurobagel/neurobagel_examples
    neurobagel/openneuro-annotations
    neurobagel/planning
    neurobagel/proc_dash
    neurobagel/project
    neurobagel/project
    neurobagel/query-tool
    neurobagel/workflows
  files: 
    - source: template_workflows/
      dest: .github/workflows/
